import type { Metadata } from "next";
// import localFont from "next/font/local";
import {JetBrains_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Transition from "@/components/Transition";
import StairTransition from "@/components/StairTransition";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300",  "400","500","600", "700","800"],
  variable: "--font-jetbrainsMono"
});
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Portfolio of Amjaad Rana",
  description: "Generated by Amjaad Rana .A modern, sleek, and responsive portfolio website designed to showcase your expertise as a Full Stack Web Developer and MERN Stack Specialist. The site highlights your skills in React.js, Node.js, and MongoDB, and features an intuitive interface to display your projects, work experience, and technical proficiency.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={jetbrainsMono.variable
          // `${geistSans.variable} ${geistMono.variable

          }
      >
          <Header />
          <StairTransition/>
        <Transition>
          {children}
        </Transition>
      </body>
    </html>
  );
}
